columnSuffix: null
contentColumnType: string
fieldGroup: 44b77bba-4e86-470a-b7a7-5e11e6d2c210 # Common
handle: images
instructions: ''
name: Images
searchable: false
settings:
  allowSelfRelations: false
  allowUploads: true
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:9bdd7649-336f-4968-bee0-cc914c191f18' # Images
  defaultUploadLocationSubpath: ''
  limit: ''
  localizeRelations: false
  previewMode: full
  restrictFiles: '1'
  selectionLabel: ''
  showSiteMenu: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:9bdd7649-336f-4968-bee0-cc914c191f18' # Images
  singleUploadLocationSubpath: ''
  source: null
  sources:
    - 'volume:9bdd7649-336f-4968-bee0-cc914c191f18' # Images
  targetSiteId: null
  useSingleFolder: false
  validateRelatedElements: false
  viewMode: large
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
