columnSuffix: qmxkcsnd
contentColumnType: text
fieldGroup: 44b77bba-4e86-470a-b7a7-5e11e6d2c210 # Common
handle: pageContent
instructions: ''
name: 'Page Content'
searchable: false
settings:
  availableTransforms: '*'
  availableVolumes: '*'
  columnType: text
  defaultTransform: ''
  initJs: null
  purifierConfig: ''
  purifyHtml: '1'
  removeEmptyTags: false
  removeInlineStyles: false
  removeNbsp: false
  showUnpermittedFiles: ''
  showUnpermittedVolumes: ''
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
