dateModified: 1730267638
email:
  fromEmail: jgreentreevin@gmail.com
  fromName: 'Church Online'
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    5ac11c1a-4c54-4be3-b52e-a2b6ca22829b: 'Church Online' # Church Online
    9bdd7649-336f-4968-bee0-cc914c191f18: Images # Images
    44b77bba-4e86-470a-b7a7-5e11e6d2c210: Common # Common
    696178da-83aa-45ce-9014-21667762d6b8: 'Church Online' # Church Online
    afe859ab-a824-4cb6-b0d3-f5ac4875f6dc: Live # Live
    e38b3013-2388-4553-8e5e-bdb2c7049481: Images # Images
    f27f97d3-7d16-47cd-8f60-2e2115f89def: Live # Live
    ff93bb62-24e0-4fe9-8f03-0c63b76fdffd: 'Page Content' # Page Content
plugins:
  cheat-sheet:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
    settings:
      cheatSheetRoute: cheatsheet
      cheatSheetWhitespace: \t
  ckeditor:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  help-links:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  sprig:
    edition: standard
    enabled: true
    schemaVersion: 1.0.1
  twigpack:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  youtubeliveembed:
    edition: standard
    enabled: true
    schemaVersion: 1.0.10
    settings:
      isLive: '1'
      youtubeChannelId: UCTIKg0f0UuTN9jxxuL-EnNA
system:
  edition: pro
  live: true
  name: 'Church Online'
  schemaVersion: 3.8.0.1
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
