defaultPlacement: end
enableVersioning: true
handle: homepage
name: Homepage
propagationMethod: all
siteSettings:
  81c2dcc1-a484-47d8-8c82-7a135bcdee50: # JayGreentree
    enabledByDefault: true
    hasUrls: true
    template: index.twig
    uriFormat: __home__
type: single
