defaultPlacement: end
enableVersioning: true
handle: live
name: Live
propagationMethod: all
siteSettings:
  5ac11c1a-4c54-4be3-b52e-a2b6ca22829b: # Church Online
    enabledByDefault: true
    hasUrls: true
    template: index.twig
    uriFormat: __home__
type: single
